- name: group:somegroup@some.org
  policies:
    - type: project
      name: a-project-name
      role: editor
- name: user:someuser@some.org
  policies:
    - type: project
      name: a-project-name
      role: bigquery.jobUser
      max_minutes: 10
    - type: project
      name: a-project-name
      role: browser
