- name: group:security@einride.tech
  policies:
    - type: project
      name: e-security-experiments
      role: editor
- name: user:patrik.nordlen@einride.tech
  policies:
    - type: project
      name: e-security-experiments
      role: bigquery.jobUser
      max_minutes: 10
    - type: project
      name: e-security-experiments
      role: browser
- name: user:anton.sapozhnikov@einride.tech
  policies:
    - type: project
      name: e-security-experiments
      role: browser
